package sdk

const (
	COMMANDID_PING              = 0x00
	COMMANDID_ERROR             = 0x01
	COMMANDID_GET_MAC           = 0x02
	COMMANDID_JMCP              = 0x06
	COMMANDID_LOGIN             = 0x10
	COMMANDID_GET_NAME          = 0x26
	COMMANDID_HM_GET_TRANSITION = 0x70
	COMMANDID_JMCP_RESPONSE     = COMMANDID_JMCP | 0x80
	COMMANDID_LOGIN_RESPONSE    = COMMANDID_LOGIN | 0x80
)
