package sdk

const (
	RESPONSE_MASK = 0x80

	COMMANDID_PING              = 0x00
	COMMANDID_ERROR             = 0x01
	COMMANDID_GET_MAC           = 0x02
	COMMANDID_JMCP              = 0x06
	COMMANDID_LOGIN             = 0x10
	COMMANDID_LOGOUT            = 0x11
	COMMANDID_GET_NAME          = 0x26
	COMMANDID_SET_STATE         = 0x33
	COMMANDID_HM_GET_TRANSITION = 0x70

	COMMANDID_PING_RESPONSE              = COMMANDID_PING | RESPONSE_MASK
	COMMANDID_GET_MAC_RESPONSE           = COMMANDID_GET_MAC | RESPONSE_MASK
	COMMANDID_JMCP_RESPONSE              = COMMANDID_JMCP | RESPONSE_MASK
	COMMANDID_LOGIN_RESPONSE             = COMMANDID_LOGIN | RESPONSE_MASK
	COMMANDID_LOGOUT_RESPONSE            = COMMANDID_LOGOUT | RESPONSE_MASK
	COMMANDID_GET_NAME_RESPONSE          = COMMANDID_GET_NAME | RESPONSE_MASK
	COMMANDID_SET_STATE_RESPONSE         = COMMANDID_SET_STATE | RESPONSE_MASK
	COMMANDID_HM_GET_TRANSITION_RESPONSE = COMMANDID_HM_GET_TRANSITION | RESPONSE_MASK

	PORT_TYPE_NONE       = 0
	PORT_TYPE_IMPULS     = 1
	PORT_TYPE_AUTO_CLOSE = 2
	PORT_TYPE_ON_OFF     = 3
	PORT_TYPE_UP         = 4
	PORT_TYPE_DOWN       = 5
	PORT_TYPE_HALF       = 6
	PORT_TYPE_WALK       = 7
	PORT_TYPE_LIGHT      = 8
	PORT_TYPE_ON         = 9
	PORT_TYPE_OFF        = 10
	PORT_TYPE_LOCK       = 11
	PORT_TYPE_UNLOCK     = 12
	PORT_TYPE_OPEN_DOOR  = 13
	PORT_TYPE_LIFT       = 14
	PORT_TYPE_SINK       = 15
)
