package sdk

const (
	RESPONSE_MASK = 0x80

	COMMANDID_PING              = 0x00
	COMMANDID_ERROR             = 0x01
	COMMANDID_GET_MAC           = 0x02
	COMMANDID_JMCP              = 0x06
	COMMANDID_LOGIN             = 0x10
	COMMANDID_LOGOUT            = 0x11
	COMMANDID_GET_NAME          = 0x26
	COMMANDID_SET_STATE         = 0x33
	COMMANDID_HM_GET_TRANSITION = 0x70

	COMMANDID_PING_RESPONSE              = COMMANDID_PING | RESPONSE_MASK
	COMMANDID_GET_MAC_RESPONSE           = COMMANDID_GET_MAC | RESPONSE_MASK
	COMMANDID_JMCP_RESPONSE              = COMMANDID_JMCP | RESPONSE_MASK
	COMMANDID_LOGIN_RESPONSE             = COMMANDID_LOGIN | RESPONSE_MASK
	COMMANDID_LOGOUT_RESPONSE            = COMMANDID_LOGOUT | RESPONSE_MASK
	COMMANDID_GET_NAME_RESPONSE          = COMMANDID_GET_NAME | RESPONSE_MASK
	COMMANDID_SET_STATE_RESPONSE         = COMMANDID_SET_STATE | RESPONSE_MASK
	COMMANDID_HM_GET_TRANSITION_RESPONSE = COMMANDID_HM_GET_TRANSITION | RESPONSE_MASK
)
